### ISSUE TITLE
hahaha Interesting work~

### ISSUE THREAD

**Issue by ssocean** [SpatialVision/Orient-Anything#2]
![image](https://github.com/user-attachments/assets/a1e853f2-b799-4905-9383-d0eaab1982c7)

**Comment by ssocean** [comment]
![image](https://github.com/user-attachments/assets/e56eaed2-a11b-4ccd-9e97-868c6b536f1b)
篮球也是一个有趣的例子

**Comment by ssocean** [comment]
![image](https://github.com/user-attachments/assets/ecb30e56-2d82-4350-ab89-7e54d0e56d11)

**Comment by zehanwang01** [comment]
Sorry for your misunderstanding due to some unexplained details. The Orientation Anything model outputs confidence to evaluate whether the object has a meaningful orientation. For the three cases you provided, the predicted confidences are very low, which means that our model believes that these objects may not have a meaningful front face and orientation.
<img width="1333" alt="iShot_2024-12-25_21 47 46" src="https://github.com/user-attachments/assets/d0de7324-7702-48cc-9964-f3c203e2a5c7" />
<img width="1260" alt="iShot_2024-12-25_21 48 34" src="https://github.com/user-attachments/assets/f928e205-e284-4bcc-a876-2a91b97d00f5" />
<img width="1240" alt="iShot_2024-12-25_21 49 08" src="https://github.com/user-attachments/assets/b6b7600a-c7b3-4860-9e8b-d80eaa60c29d" />

We will polish the presentation of our demo to avoid such misunderstandings. We are open to further bad cases, which is the main direction for us to improve our model.

**Comment by ssocean** [comment]
Thank you for your professional explanation. The output confidence is a great design. I'm not specialized in this field, but I find your approach really interesting, and it could have broader applications in many other tasks~ Solid work
